const dayValues = {
  1: {
    headings: [ "EVENT-1 DAY-1.....",
     "EVENT-2 DAY-1.....",
     "EVENT-3 DAY-1.....",
     "EVENT-4 DAY-1.....",],
    date: "18 Jan 2024",
    subheadings: [ "EVENT-1 DAY-1.....",
    "EVENT-2 DAY-1.....",
    "Coming soon.....",
    "Coming soon.....",
    "Coming soon.....",],
  },
  2: {
    headings: [ "EVENT-1 DAY-2.....",
     "EVENT-2 DAY-2.....",
     "EVENT-3 DAY-2.....",
     "EVENT-4 DAY-2.....",],
    date: "19 Jan 2024",
    subheadings: [ "EVENT-1 DAY-2.....",
    "EVENT-2 DAY-2.....",
    "Coming soon.....",
    "Coming soon.....",
    "Coming soon.....",],
  },
  3: {
    headings: [ "EVENT-1 DAY-3.....",
     "EVENT-2 DAY-3.....",
     "EVENT-3 DAY-3.....",
     "EVENT-4 DAY-3.....",
     "EVENT-3 DAY-3.....",
     "EVENT-4 DAY-3.....",],
    date: "20 Jan 2024",
    subheadings: [ "EVENT-1 DAY-3.....",
    "EVENT-2 DAY-3.....",
    "Coming soon.....",
    "Coming soon.....",
    "Coming soon.....",
    "Coming soon.....",
    "Coming soon.....",],
  },
  4: {
    headings: [ "EVENT-1 DAY-4.....",
     "EVENT-2 DAY-4.....",
     "EVENT-3 DAY-4.....",
     "EVENT-4 DAY-4.....",],
    date: "21 Jan 2024",
    subheadings: [ "EVENT-1 DAY-4.....",
    "EVENT-2 DAY-1.....",
    "Coming soon.....",
    "Coming soon.....",
    "Coming soon.....",],
  },
};

export default dayValues;
