const dayValues = {
  1: {
    block1: "Coming soon.....",
    block2: "Coming soon.....",
    block3: "Coming soon.....",
    block4: "Coming soon.....",
    block5: "Coming soon.....",
    block6: "Coming soon.....",
    block7: "Coming soon.....",
    block8: "Coming soon.....",
    date: "18 Jan 2024",
    infoBlock1: "Coming soon.....",
    infoBlock2: "Coming soon.....",
    infoBlock3: "Coming soon.....",
    infoBlock4: "Coming soon.....",
    infoBlock5: "Coming soon.....",
    infoBlock6: "Coming soon.....",
    infoBlock7: "Coming soon.....",
    infoBlock8: "Coming soon.....",
  },
  2: {
    block1: "Coming soon.....",
    block2: "Coming soon.....",
    block3: "Coming soon.....",
    block4: "Coming soon.....",
    block5: "Coming soon.....",
    block6: "Coming soon.....",
    block7: "Coming soon.....",
    block8: "Coming soon.....",
    date: "19 Jan 2024",
    infoBlock1: "Coming soon.....",
    infoBlock2: "Coming soon.....",
    infoBlock3: "Coming soon.....",
    infoBlock4: "Coming soon.....",
    infoBlock5: "Coming soon.....",
    infoBlock6: "Coming soon.....",
    infoBlock7: "Coming soon.....",
    infoBlock8: "Coming soon.....",
  },
  3: {
    block1: "Coming soon.....",
    block2: "Coming soon.....",
    block3: "Coming soon.....",
    block4: "Coming soon.....",
    block5: "Coming soon.....",
    block6: "Coming soon.....",
    block7: "Coming soon.....",
    block8: "Coming soon.....",
    date: "20 Jan 2024",
    infoBlock1: "Coming soon.....",
    infoBlock2: "Coming soon.....",
    infoBlock3: "Coming soon.....",
    infoBlock4: "Coming soon.....",
    infoBlock5: "Coming soon.....",
    infoBlock6: "Coming soon.....",
    infoBlock7: "Coming soon.....",
    infoBlock8: "Coming soon.....",
  },
  4: {
    block1: "Coming soon.....",
    block2: "Coming soon.....",
    block3: "Coming soon.....",
    block4: "Coming soon.....",
    block5: "Coming soon.....",
    block6: "Coming soon.....",
    block7: "Coming soon.....",
    block8: "Coming soon.....",
    date: "21 Jan 2024",
    infoBlock1: "Coming soon.....",
    infoBlock2: "Coming soon.....",
    infoBlock3: "Coming soon.....",
    infoBlock4: "Coming soon.....",
    infoBlock5: "Coming soon.....",
    infoBlock6: "Coming soon.....",
    infoBlock7: "Coming soon.....",
    infoBlock8: "Coming soon.....",
  },
};

export default dayValues;
