const eventContent = [[
  {
    title: "DevComm 2023",
    date: "January 18, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  
  {
    title: "DevComm 2023",
    date:"January 18, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date: "January 18, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date: "January 18, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date:  "January 18, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date:  "January 18, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date: "January 18, 2024",
    time_span: "8:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date:  "January 18, 2024",
    time_span: "10:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
], [
  {
    title: "DevComm 2023",
    date: "January 19, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  
  {
    title: "DevComm 2023",
    date:"January 19, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date: "January 19, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date: "January 19, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date:"January 19, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date:"January 19, 2024",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date:"January 19, 2024",
    time_span: "8:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
  {
    title: "DevComm 2023",
    date: "January 19, 2024",
    time_span: "10:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    no_of_participants: 0,
  },
], [{
  title: "DevComm 2023",
  date: "January 20, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an einnovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},

{
  title: "DevComm 2023",
  date: "January 20, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date:"January 20, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date: "January 20, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date: "January 20, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date: "January 20, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date:"January 20, 2024",
  time_span: "8:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date:"January 20, 2024",
  time_span: "10:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},], [{
  title: "DevComm 2023",
  date:"January 21, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},

{
  title: "DevComm 2023",
  date: "January 21, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date: "January 21, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date:"January 21, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date: "January 21, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date:"January 21, 2024",
  time_span: "9:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date: "January 21, 2024",
  time_span: "8:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},
{
  title: "DevComm 2023",
  date: "January 21, 2024",
  time_span: "10:00 AM - 5:00 PM",
  location: "Main Campus, Dwarka",
  organizer: "DevComm",
  event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
  no_of_participants: 0,
},]];

export default eventContent;