const eventContent = [
  {
    title: "DevComm 2023",
    date: "March 15, 2023",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    agenda: "Opening Ceremony, Coding Sessions, Project Demos, Awards Ceremony",
    speakers: "DevComm Organizers",
    registration_info: "Register online at www.devcommhackathon.com",
    no_of_participants: 500,
  },
  
  {
    title: "DevComm 2023",
    date: "March 15, 2023",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    agenda: "Opening Ceremony, Coding Sessions, Project Demos, Awards Ceremony",
    speakers: "DevComm Organizers",
    registration_info: "Register online at www.devcommhackathon.com",
    no_of_participants: 500,
  },
  {
    title: "DevComm 2023",
    date: "March 15, 2023",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    agenda: "Opening Ceremony, Coding Sessions, Project Demos, Awards Ceremony",
    speakers: "DevComm Organizers",
    registration_info: "Register online at www.devcommhackathon.com",
    no_of_participants: 500,
  },
  {
    title: "DevComm 2023",
    date: "March 15, 2023",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    agenda: "Opening Ceremony, Coding Sessions, Project Demos, Awards Ceremony",
    speakers: "DevComm Organizers",
    registration_info: "Register online at www.devcommhackathon.com",
    no_of_participants: 500,
  },
  {
    title: "DevComm 2023",
    date: "March 15, 2023",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    agenda: "Opening Ceremony, Coding Sessions, Project Demos, Awards Ceremony",
    speakers: "DevComm Organizers",
    registration_info: "Register online at www.devcommhackathon.com",
    no_of_participants: 500,
  },
  {
    title: "DevComm 2023",
    date: "March 15, 2023",
    time_span: "9:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    agenda: "Opening Ceremony, Coding Sessions, Project Demos, Awards Ceremony",
    speakers: "DevComm Organizers",
    registration_info: "Register online at www.devcommhackathon.com",
    no_of_participants: 500,
  },
  {
    title: "DevComm 2023",
    date: "March 15, 2023",
    time_span: "8:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    agenda: "Opening Ceremony, Coding Sessions, Project Demos, Awards Ceremony",
    speakers: "DevComm Organizers",
    registration_info: "Register online at www.devcommhackathon.com",
    no_of_participants: 500,
  },
  {
    title: "DevComm 2023",
    date: "March 15, 2023",
    time_span: "10:00 AM - 5:00 PM",
    location: "Main Campus, Dwarka",
    organizer: "DevComm",
    event_info: "Join us for an exciting hackathon filled with innovation, coding challenges, and collaboration.",
    agenda: "Opening Ceremony, Coding Sessions, Project Demos, Awards Ceremony",
    speakers: "DevComm Organizers",
    registration_info: "Register online at www.devcommhackathon.com",
    no_of_participants: 500,
  },
];

export default eventContent;